FROM jenkins/jenkins:lts

USER jenkins

# Instalação dos plugin necessário
RUN jenkins-plugin-cli --plugins blueocean:1.25.5 build-timestamp:1.0.3 timestamper:1.17 pollscm:1.3.1 github-api:1.321-488.v9b_c0da_9533f8

USER root

# Configurações de ambiente
ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"
ENV ACCESS_KEY ${ACCESS_KEY}
ENV SECRET_KEY ${SECRET_KEY}

# Instalar pacotes necessários para criar o ambiente virtual
RUN apt update && \
    apt install -y python3 python3-pip python3-venv

# Criar um ambiente virtual
RUN python3 -m venv /usr/src/app/venv

# Garantir que o Python do ambiente virtual seja usado
ENV PATH="/usr/src/app/venv/bin:$PATH"

# Copiar requirements.txt para o container
COPY ./requirements.txt /usr/src/app/requirements.txt

# Instalar as dependências dentro do ambiente virtual
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt

# Copiar arquivos de configuração do Jenkins
COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy